config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  
  devise_for :users

  put 'answers/:id/choose_best_answer',
      controller: 'answers',
      action: 'choose_best_answer',
      as: 'choose_best_answer'

  delete '/attachments/:id', 
  	  controller: 'attachments',
  	  action: 'destroy',
  	  as: 'destroy_attachment'

  resources :questions do
    resources :answers, shallow: true
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy 

  validates :body, :question_id, :user_id, presence: true
  validates :body, length: { minimum: 10 }
  validates :is_best, inclusion: { in: [true, false] }

  accepts_nested_attributes_for :attachments

  def belongs?(user)
    self.user.id == user.id if self.user.present? && user.present?
  end

  def make_best!
    transaction do
      question.answers.update_all(is_best: false)
      update! is_best: true
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
	belongs_to :attachable, polymorphic: true, optional: true		
	mount_uploader :file, FileUploader
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, -> { order 'is_best desc' }, dependent: :destroy  
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :title, :body, :user_id, presence: true
  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 10 }

  accepts_nested_attributes_for :attachments

  def belongs?(user)
    self.user.id == user.id if self.user.present? && user.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers

  validates :email, :password, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :authenticate_user!
  before_action :find_question, only: [:create]
  before_action :find_answer, only: [:update, :choose_best_answer, :destroy]

  def create
    @answer = @question.answers.create answer_params
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update answer_params
  end

  def choose_best_answer
    @question = @answer.question
    @answer.make_best!
  end

  def destroy
    @question = @answer.question
    @answer.destroy
  end

  private

  def find_answer
    @answer = Answer.find params[:id]
  end

  def find_question
    @question = Question.find params[:question_id]
  end

  def answer_params
    params.require(:answer).permit(:body, :is_best, attachments_attributes: [:file])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
	before_action :authenticate_user!

	before_action :find_attachment
	before_action :find_question
	before_action :find_answer

	def destroy
		@attachment.destroy	
	end

	private 

	def find_attachment
		@attachment = Attachment.find params[:id]
	end

	def find_question
		@question = Question.find(@attachment.attachable_id) if @attachment.attachable_type == 'Question'
	end

	def find_answer
		@answer = Answer.find(@attachment.attachable_id) if @attachment.attachable_type == 'Answer'
	end	
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :update, :destroy]  

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.attachments.new
    @question.attachments.new
  end

  def new
    @question = Question.new 
    @question.attachments.new
  end

  def create
    @question = Question.new question_params
    @question.user = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      redirect_to new_question_path, notice: "Question not saved. Check attributes."
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if @question.destroy
      redirect_to questions_path
    else
      render :edit, notice: 'You cannot delete this question'
    end
  end

  private

  def find_user
    @user = User.find params[:user_id]
  end

  def find_question
    @question = Question.find params[:id]
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id])
  end
end

app/views/answers/_add_answer.html.slim
tr
  td
    span id="answer-#{@answer.id}"
      = @answer.body
tr
  td
    ul
      - @answer.attachments.each do |a|          
        li= link_to a.file.identifier, a.file.url
tr
  - if @answer.belongs? current_user
  td
      = link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: @answer.id }
      = render partial: 'answers/edit_form', locals: {answer: @answer}
  td
    = link_to 'Remove answer', answer_path(@answer), remote: true, method: :delete
  - if @question.belongs? current_user
    td
      = link_to 'Best answer', choose_best_answer_path(@answer), remote: true, method: :put

app/views/answers/_create_form.html.slim
table
  tr
    td
      = form_for [@question, @answer], remote: true do |answer_form|
        = answer_form.label :body, "Ask or answer"
        = answer_form.hidden_field :is_best, value: false
        br
        = answer_form.text_area :body
        br
        = answer_form.fields_for :attachments do |attach_form|
          = attach_form.label :file
          = attach_form.file_field :file
        br
        = answer_form.submit 'Create answer'

app/views/answers/_edit_form.html.slim
= form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |form|
  = form.hidden_field :is_best, value: false
  = form.label :body, "Answer body"
  br
  = form.text_area :body
  br
  = form.submit 'Change answer'

app/views/answers/_message.html.slim
- if @answer.errors.any?        
  - @answer.errors.full_messages.each do |msg|
    p = msg

app/views/answers/choose_best_answer.js.erb
$('div.answers').html('<%= j render 'questions/answers' %>');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>  
	$('#errors').html("<%= j render 'message' %>");
<% else %>
	$('.answers').append('<%= j render "add_answer" %>');
  	$('#answer_body').val('');
  	$('#create_errors').empty();  
<% end %>

app/views/answers/destroy.js.erb
$('div.answers').html('<%= j render 'questions/answers' %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  $('#errors').html("<%= j render 'message' %>");
<% else %>
  $('#answer-<%= @answer.id %>').html('<%= @answer.body %>');
  $('form#edit-answer-<%= @answer.id %>').hide();
<% end %>

app/views/attachments/destroy.js.erb
$('div.question_info').html('<%= j render 'questions/question_info' %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p><%= link_to 'Log out', destroy_user_session_path, method: :delete %></p>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/_answers.html.slim
b = 'Answers for this question:'
table
  - @question.answers.each do |answer|
    tr
      td
        span id="answer-#{answer.id}"
          - if answer.is_best
            #best_answer
              = answer.body
          - else
            = answer.body
    tr
      td
        ul
          - answer.attachments.each do |a|          
            li = link_to a.file.identifier, a.file.url
    tr
      - if answer.belongs? current_user
	    td
          = link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: answer.id }
          = render partial: 'answers/edit_form', locals: {answer: answer}
	    td
	      = link_to 'Remove answer', answer_path(answer), remote: true, method: :delete

      - if @question.belongs? current_user
        td
          = link_to 'Best answer', choose_best_answer_path(answer), remote: true, method: :put

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
    br
    = f.file_field :file
  = link_to_remove_association "remove file", f

app/views/questions/_edit_question_form.html.slim
= form_for @question, remote: true, html: {id: "edit-question-form"} do |form|
  table
    tr
      td
        = form.label :title, 'Question title'
      td
        = form.text_field :title
    tr
      td
        = form.label :body, 'Question body'
      td
        = form.text_area :body
    / tr
    /   td
    /     = form.fields_for :attachments do |attach_form|
    /       = attach_form.label :file
    /       = attach_form.file_field :file
    tr
      td
        = form.fields_for :attachments do |attach_form|
          =render 'attachment_fields', f: attach_form          
        .links
          = link_to_add_association "Add another file", form, :attachments
    tr
      td
        = form.submit 'Change question'

app/views/questions/_message.html.slim
- if @question.errors.any?
  - @question.errors.full_messages.each do |msg|
    p = msg

app/views/questions/_question_info.html.slim
p
  b = 'Question information'
br
  p = @question.title
  p = @question.body

#question_attachments
  p Attachments:
  ul
    - @question.attachments.each do |attachment|
      - if attachment.persisted?
        li 
          = link_to attachment.file.identifier, attachment.file.url 
          = link_to 'Delete', destroy_attachment_path(attachment), remote: true, method: :delete if @question.belongs? current_user

app/views/questions/index.html.slim
b 'List of questions'
br

ul
- for question in @questions
  li = link_to question.title, question_path(question)

p = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  table
    tr
	  td
	    = f.label :title
	  td
	    = f.text_field :title
	tr
	  td
	    = f.label :body
	  td
	    = f.text_area :body
	tr
	  td
	    = 'Attachments:'
	tr
	  td
	  	= f.fields_for :attachments do |attach_form|
	  	  = attach_form.label :file
	   	  = attach_form.file_field :file
    tr
	  td
	  	= f.submit 'Create question'

app/views/questions/show.html.slim
#errors

.question_info
  = render 'question_info'

- if @question.belongs? current_user
  p
    = link_to 'Edit question', '', id: 'edit-question-link'
    = render 'edit_question_form'
    = link_to 'Remove question', @question, method: :delete

.answers
  = render 'answers'

.answer_form
  - if current_user
    = render 'answers/create_form'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('#errors').html("<%= j render 'message' %>");
<% else %>
  $('div.question_info').html('<%= j render 'question_info' %>');
  $('#edit-question-form').hide();
<% end %>